### ISSUE TITLE
error 404 not found

### ISSUE THREAD

**Issue by topstresser** [redianmarku/Telegram-Member-Adder#1]
Traceback (most recent call last):
  File "main1.639.py", line 1430, in <module>
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "main1.639.py", line 197, in main
ValueError: could not convert string to float: '404: Not Found'

**Comment by Ben10Ken** [comment]
Traceback (most recent call last):
  File "main1.639.py", line 149, in main
  File "<frozen genericpath>", line 62, in getsize
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable: 'credentials.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main1.639.py", line 1430, in <module>
  File "C:\Users\bpall\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\bpall\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bpall\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "main1.639.py", line 154, in main
  File "main1.639.py", line 112, in convert_old_cre_into_new
  File "<frozen genericpath>", line 62, in getsize
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable: 'credentials.csv'

**Comment by Ben10Ken** [comment]
Traceback (most recent call last):
  File "main1.639.py", line 149, in main
  File "<frozen genericpath>", line 62, in getsize
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable: 'credentials.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main1.639.py", line 1430, in <module>
  File "C:\Users\bpall\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\bpall\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bpall\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "main1.639.py", line 154, in main
  File "main1.639.py", line 112, in convert_old_cre_into_new
  File "<frozen genericpath>", line 62, in getsize
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable: 'credentials.csv'

**Comment by Ben10Ken** [comment]
I have the same issue :

Traceback (most recent call last):
  File "main1.639.py", line 1430, in <module>
  File "C:\Users\bpall\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\bpall\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bpall\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "main1.639.py", line 197, in main
ValueError: could not convert string to float: '404: Not Found'

**Comment by PiseyPhal** [comment]
Traceback (most recent call last):
  File "main1.639.py", line 1430, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "main1.639.py", line 197, in main
ValueError: could not convert string to float: '404: Not Found'

**Comment by cryptogambleraddict** [comment]
Did you found the solution?

**Comment by topstresser** [comment]
nah
